kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APPNAVN }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  envFrom:
    - secret: {{ DOKPROD_INFOTRYGDBREV_SECRET }}
    - configmap: {{ DOKPROD_INFOTRYGDBREV_CONFIGMAP }}
  filesFrom:
    - secret: {{ DOKPROD_INFOTRYGDBREV_SECRET }}
      mountPath: "/var/run/secrets/nais_secrets"
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-Djavax.net.ssl.keyStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.keyStorePassword=$(NAV_TRUSTSTORE_PASSWORD)
              -Djavax.net.ssl.keyStoreType=jks
              -Dio.netty.allocator.type=pooled
              -XX:MaxRAMPercentage=75
              $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: DOKPROD_INFOTRYGDBREV_ENDPOINTS_PDL_URL
      value: {{ DOKPROD_INFOTRYGDBREV_ENDPOINTS_PDL_URL }}
    - name: DOKPROD_INFOTRYGDBREV_ENDPOINTS_PDL_SCOPE
      value: {{ DOKPROD_INFOTRYGDBREV_ENDPOINTS_PDL_SCOPE }}
    - name: DOKPROD_INFOTRYGDBREV_ENDPOINTS_SAK_URL
      value: {{ DOKPROD_INFOTRYGDBREV_ENDPOINTS_SAK_URL }}
    - name: DOKPROD_INFOTRYGDBREV_ENDPOINTS_SAK_SCOPE
      value: {{ DOKPROD_INFOTRYGDBREV_ENDPOINTS_SAK_SCOPE }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: DOKPROD_INFOTRYGDBREV_QDOK001_QUEUENAME
      value: {{ DOKPROD_INFOTRYGDBREV_QDOK001_QUEUENAME }}
    - name: SPRING_DATASOURCE_URL
      value: "$(NAIS_DATABASE_DOKPROD_INFOTRYGDBREV_DOKPROD_INFOTRYGDBREV_JDBC_URL)"
    - name: SPRING_DATASOURCE_USERNAME
      value: "$(NAIS_DATABASE_DOKPROD_INFOTRYGDBREV_DOKPROD_INFOTRYGDBREV_USERNAME)"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "$(NAIS_DATABASE_DOKPROD_INFOTRYGDBREV_DOKPROD_INFOTRYGDBREV_PASSWORD)"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment.name={{ ENVIRONMENT }}"
    - name: SFTP_PRIVATE_KEY_FILE
      value: "/var/run/secrets/nais_secrets/sftp_privatekey_file"
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 10m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-f1-micro
        databases:
          - name: DOKPROD_INFOTRYGDBREV
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      external:
        - host: {{ MQGATEWAY01_HOSTNAME }}
          ports:
            - port: {{ MQGATEWAY01_PORT }}
  azure:
    application:
      enabled: true
